### ISSUE TITLE
[FR] localization with variables

### ISSUE THREAD

**Issue by hyochan** [prisma-korea/prisma-nextjs-rsc#3]
Get idea from https://dev.to/ajones_codes/the-ultimate-guide-to-internationalization-i18n-in-nextjs-13-ed0 and findout the best solution to apply to our template

**Comment by ghost** [comment]
@hyochan you can close this issue https://github.com/prisma-korea/prisma-nextjs-rsc/pull/5#event-9626719123

**Comment by hyochan** [comment]
@deutschkihun Sure. Next time consider auto closing issue when PR is merged.
https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

Closes via #5
